### ISSUE TITLE
Lage noen frie oppgaver til de som kommer langt 

### ISSUE THREAD

**Issue by Hindenes** [bekk/react-native-workshop#49]
Feks. bridging av noe native-kode
Mer avansert layout?
Få opp bilder i fullskjerm når de blir klikket på?
Ta i bruk en tredjepartsmodul helt på egenhånd?

Flere forslag?

**Comment by Lomaas** [comment]
Edit message:
- Send the user to NewMessage component to edit message. Send with the state of the message and prefill the view.
- Create an action and a reducer to handle edit message. 

Delete message:
- iOS: Listen for swipe gesture on the messages. Use the native list view handling like the standard Mail app. Create a action and reducer for deletion. 
- Android: Long press to delete?

**Comment by Lomaas** [comment]
iOS: 3D touch on a message gives you a preview of the message

**Comment by Hindenes** [comment]
Done
