### ISSUE TITLE
Bruk av deres Image komponent i bildeopplastingen feiler

### ISSUE THREAD

**Issue by trondkla** [bekk/react-native-workshop#73]
<img width="379" alt="screenshot 2016-04-15 14 53 03" src="https://cloud.githubusercontent.com/assets/464589/14561898/d8dd3e7a-0319-11e6-928f-1398172f1497.png">

**Comment by trondkla** [comment]
Kan reproduseres ved å bruke deres Image klasse i oppgave 4.

**Comment by Hindenes** [comment]
Fikser denne ved å fjerne vår image-klasse fra master og exercise-1. Klassen brukes som en del av vårt løsningsforslag i oppgave 2, og trenger derfor ikke å eksistere i koden før det.
