### ISSUE TITLE
Fjern react-native-camera i alle branches (ligger i en egen branch nå)

### ISSUE THREAD

**Issue by Hindenes** [bekk/react-native-workshop#81]

**Comment by Hindenes** [comment]
Tror det holder å fjerne fra package.json i exersise-4 (siden vi skal branche ut på nytt i august) her. Det ser ut som at native-bibliotekene til react-native-camera er fjernet fra både Android og iOS i den branchen

**Comment by nutgaard** [comment]
Ser ut som det fortsatt ligger inne for android: https://github.com/bekk/react-native-workshop/blob/exercise-4/android/app/build.gradle#L123
